# Site settings
title: Bonum Quant Research
email: bonum@proton.ch
description: > # this means to ignore newlines until "baseurl:"
  Bonum Quant Research is a quantitative investing boutique
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
